# Generated by Django 6.1.1 on 2026-09-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='financialevent',
            new_name='financial_e_user_id_2c7e6a_idx',
            old_name='financial_e_user_id_dfc43f_idx',
        ),
        migrations.RenameIndex(
            model_name='financialevent',
            new_name='financial_e_categor_7c06ab_idx',
            old_name='financial_e_categor_e3fe65_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messages_user_id_5de4c8_idx',
            old_name='messages_user_id_8b2930_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaserequest',
            new_name='purchase_re_user_id_18f994_idx',
            old_name='purchase_re_user_id_348670_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaserequest',
            new_name='purchase_re_is_samp_7ec99e_idx',
            old_name='purchase_re_is_samp_c9158c_idx',
        ),
    ]
